---
bibliography: references.bib
---

# Background: Sensitization Memory in *Aplysia*

## Sensitization is a conserved and adaptive form of non-associative pain memory

Sensitization is a non-associative form of memory for painful experiences; it is expressed as a generalized increase in responsiveness that persists after exposure to a noxious stimulation [@thompson1966].  Sensitization memory helps organisms that have experienced pain re-allocate their behavioral repertoire to avoid additional injury, aiding the chances of survival [@crook2014].  Sensitization is observed across the animal kingdom [@abramson1994] and has been hypothesized to represent basal memory mechanisms from which more complex forms of memory evolved [@hawkins1984].  Mechanistically, sensitization shares many characteristics with clinical dysregulation of pain processing, including allodynia and hyperalgesia [@walters2023]. 

## Aplysia are marine mollusks especially suitable for exploring the neurobiology of memory

*Aplysia* is a genus of marine gastropod useful for linking behavioral and neural plasticity (@fig-aplysia-overview).  Studies have primarily focused on *Aplysia californica*, which is found throughout much of the western coast of North America and *Aplysia kurodai,* which is found in South-East Asia.  *Aplysia* have several advantages for linking behavior to neural function: 1) they have a relatively simple CNS consisting of about 10,000 neurons [@cash1989], 2) the neural circuitry underlying several ethologically-relevant behaviors has been mapped at the single-cell level [@cleary1995c], and 3) many *Aplysia* neurons are large, enabling repeated physiological measurements, single-cell manipulation of gene expression, and single-cell qPCR [@lovell2006]. 

![**Lateral and dorsal views of an *Aplysia***. Studies of sensitization often examine defensive reflexes of the tail, the siphon (a respiratory structure), or the gill. The nervous system is internal, but this figure shows its general location, highlighting the pleural and pedal ganglia. The pleural ganglia contain many of the nociceptors that innervate the body; the pedal ganglia contain many motor neurons that contribute to defensive withdrawal. Reprinted with permission from [@wilsterman].](Picture1.png){#fig-aplysia-overview fig-align="center"}

## Painful shocks increase the duration of defensive withdrawal reflexes in Aplysia, a form of sensitization memory

In *Aplysia,* sensitization memories can be induced by attack from their natural predators, including pinching from lobsters [@mason2014; @watkins2010] and strikes from the carnivorous gastropod *Navanax* [@pepino2022].  For experimental control, though, sensitization training typically consists of the application of one or more strong electrical shocks [@pinsker1973; @scholz1987c].  The level of shock is calibrated to produce pain-related behaviors (withdrawal, inking, and escape locomotion) without causing notable tissue damage.  This ensures that any behavioral changes observed after training are due to changes in the nervous system.   

Sensitization training produces an altered behavioral state in *Aplysia:* they become more likely to exhibit escape locomotion [@stopfer1988], heart rate becomes elevated [@krontiris-litowitz1999; @marinesco2004b], and food-seeking behavior is temporarily suppressed [@acheampong2012].  The most studied behavioral phenotype, however, is the duration of defensive withdrawal reflexes [@carew1971], behaviors in which an innocuous stimulus (light touch, weak electrical shock, mild water pressure) triggers a protective retraction of sensitive body parts.  A number of different withdrawal reflexes have been studied, including the gill-withdrawal reflex, the tail-withdrawal reflex, and the siphon-withdrawal reflex (the siphon is a respiratory structure).   While details vary somewhat, each of these defensive behaviors provides a clear and robust index of sensitization memory: after sensitization training a typical animal will maintain a withdrawal reflex 2-3 times as long as before training (@fig-sensitization-of-tswr).  The strength of sensitization memory can then be tracked over time, as measurement of defensive withdrawals can be made fairly frequently without notable fatigue or habituation.  Sensitizing shocks can be applied to just one side of the body.  This produces sensitization of tail-evoked reflexes only on the side of training [@scholz1987c], allowing within-subjects experiments comparing the trained and untrained sides of the nervous system.

![**Sensitization in *Aplysia*.** In a typical sensitization experiment, defensive reflexes are measured before (top) and after (bottom) sensitization training (middle).  In this example, baseline measures are made of the tail-elicited withdrawal reflex (top). To elicit the reflex, a light stimulus is applied to the tail.  This produces a brief contraction of the tail, siphon, and gill.  The duration of contraction is used as an index of reflex strength.  After baseline measures, animals undergo sensitization training (middle).  In this example, training consists of a single painful shock applied to one side of the body (lightning bolts).  This produces inking and escape locomotion, consistent with the aversive nature of the stimulus.  Post-tests (bottom) reveal an increase in the duration of the withdrawal reflex; the increase in reflex duration is used as an index of the sensitization memory.  In this specific form of sensitization training, sensitization is only expressed on the side of the body that received training.  Training protocols applied bilaterally or at the body midline produce bilateral sensitization.  Reprinted with permission Wilsterman et al. (2023).](Picture2.png){#fig-sensitization-of-tswr}

## Serotonergic neuromodulation is a key factor in the induction of sensitization in Aplysia

The development of the sensitized state in *Aplysia* depends on shock-induced serotonin release.  Sensitization training produces prolonged activation of serotonergic fibers and increases serotonin concentrations at synapses involved in modulated behaviors [@marinesco2004b].  Depletion of serotonin prevents the development of a sensitized state [@glanzman1989], and soaking animals in serotonin produces sensitization [@bonnick2012; @levenson2000].  The close linkage between sensitization training and serotonin has enabled serotonin exposure to serve as a substitute for sensitization training not only in whole animals but also in cellular models of sensitization (see @sec-analogs-of-sensitization-memory-can-be-observed-in-whole-ganglia-and-in-cell-culture).

## Sensitization in Aplysia has short-, intermediate- and long-term phases that are distinct in mechanism and induction requirements

The seemingly unitary process of sensitization memory has been dissociated into different phases, each with distinct mechanisms operating at different time scales (@fig-lts-stages).  Three different phases of sensitization have been well-characterized [@castellucci1989; @sutton2002; @sutton2004]:

-   [Short-term sensitization]{.underline}, which develops rapidly after training but lasts less than 1 hour; this phase of memory does not require changes in translation or transcription

-   [Intermediate-term sensitization]{.underline}, which develops within 30 minutes of training and lasts less than 3 hours; this phase requires changes in translation but not transcription

-   [Long-term sensitization]{.underline}, which develops slowly (\> 6 hours) but can last for weeks; long-term sensitization requires changes in both translation and transcription 

These phases of memory have been dissociated not only by their molecular requirements but also by their induction requirements.  Very limited training (a single shock) induces only short-term sensitization that rapidly fades.  Moderate levels of training (3 spaced shocks) produces short- and intermediate-term sensitization that last several hours.  Extensive training (5 spaced shocks) induces short-, intermediate-, and long-term phases of sensitization, producing a sensitization memory expressed for several days.   This different engagement of memory mechanisms depends not only on the quantity of training but also on the pattern: massed training (5 shocks delivered in immediate sequence) fails to produce long-term sensitization [@sutton2002; @wainwright2002], and intermittent spacing can produce especially robust long-term sensitization [@Zhang2012Computational].  One of the key questions addressed in the Induction section is why only some patterns of training induce long-term sensitization.

![**Long-Term Sensitization Requires Changes in Transcription.** Sensitization has short, intermediate, and long-term phases. This figure shows the characterization of the long-term phase by its dependence on changes in gene expression. Specifically, it shows that inhibiting transcription disrupts the long-term maintenance of sensitization without altering its short- and intermediate-term expression. Data are replotted from an experiment by Sutton et al. (2001) which tracked the duration of the siphon-withdrawal reflex before and after long-term sensitization training (5 painful shocks) in a reduced preparation consisting of the siphon, tail, and nervous system. The dotted line represents no change in withdrawal duration. Control preparations (n = 7 to 12 per group) showed an immediate increase in withdrawal duration that persisted for 18 hours. Treating the nervous system with the transcriptional inhibitor actinomycin during training did not affect the induction of sensitization memory, but prevented long-term retention, with withdrawal duration returning to baseline 18 hours after training. Treatment with the transcriptional inhibitor alone (without training) did not alter withdrawal durations (data not shown).](Picture3.png){#fig-lts-stages}

## Long-term sensitization is encoded via long-term cellular, synaptic, and structural plasticity in the defensive withdrawal circuits of Aplysia

Long-term sensitization training produces a marked and long-lasting increase in the duration of defensive reflexes in *Aplysia* [@pinsker1973].  Careful work has traced the neural circuitry underlying these defensive behaviors and revealed that sensitization memory is expressed in these circuits through long-lasting changes in excitability, synaptic strength, and growth.

While details vary between the different defensive reflexes that have been studied (siphon withdrawal, tail withdrawal, gill withdrawal), each defensive reflex is mediated by a simple two-layer reflex circuit augmented by both polysynaptic pathways and neuromodulatory inputs (@fig-sensitization-mechanisms) [@cleary1995c].  Input to defensive withdrawal circuits is carried by low-threshold mechanoreceptors with cell bodies in the peripheral nervous system [@Calin-Jageman2007Behavioral; @frost1997] and high-threshold nociceptors with cell bodies in the central nervous system that innervate the siphon [@byrne1974], gill [@castellucci1970], and body wall [@walters2004; @walters1983].  The sensory neurons form excitatory glutamatergic synapses onto siphon, tail, and gill motor neurons [@dale1993; @hening1979; @hickie1995].  This direct sensory-to-motor circuit is sufficient, on its own, to produce withdrawal behaviors [@antonov1999], but motor neuron output is also sculpted by populations of interneurons that receive sensory inputs and which relay both excitation and inhibition on to reflex motor neurons [@cleary1993; @hawkins1981].  The reflex circuits in *Aplysia* are also regulated by modulatory inputs.  This includes polysynaptic innervation from neurons releasing Phe-Met-Arg-Phe-NH~2~ [FMRFa; @mackey1987], an inhibitory neuromodulator, as well as diffuse serotonergic inputs [@marinesco2004b], which serve a key role in the induction of sensitization.

![**Basic Structure of Defensive Withdrawal Circuits in *Aplysia* and Selected Changes Induced by Long-Term Sensitization.** At left is a schematic representation of shared features of defensive withdrawal reflex circuits in *Aplysia*. Sensory input is provided by mechanoreceptors (Mechano) with cell bodies in the periphery and several populations of nociceptors (Noci) with cell bodies in the central nervous system. Both populations of sensory neurons provide direct glutamatergic input to motor neurons (Motor), producing defensive withdrawal behavior. This circuit is regulated by neuromodulatory inputs, especially from serotonergic neurons (5-HT) and from a population of interneurons (Int) that provide both inhibitory and excitatory feedback. Physiological recordings (electrodes) show that long-term sensitization produces long-lasting changes throughout the defensive withdrawal circuits. Nociceptor populations form an especially prominent site of storage, and the right side of the figure shows 3 distinctive changes observed for at least 1 day after training: long-term enhancement of excitability (top), long-term facilitation (middle) and, with sufficient training, morphological changes (increases in arborization length and synaptic contacts as well as expansion of the active zones and vesicular content of existing synapses). All 3 of these long-term changes are also observed in the cellular model of sensitization in which training is simulated by repeated pulses of serotonin applied to cultures consisting of only nociceptors and their partner motor neurons. Blocking transcription during training prevents the long-term development of these physiological hallmarks of sensitization. The representative changes following sensitization are based on data from [@cleary1998b] and Wainright et al. (2002).](Picture4.png){#fig-sensitization-mechanisms}

Long-term sensitization memory is encoded at multiple sites in the defensive reflex circuits of *Aplysia*, with notable long-term changes in the input, interneuron, and motor-neuron layers [@cleary1998b; @trudeau1995].  Although encoding is diffuse, modification of the nociceptors at the input layer of the circuits represents a prominent site of storage.  These nociceptors are strongly activated by the noxious shocks used for sensitization training \[[\@walters1987](Walters,%201987a,%201987b)\].  This barrage of activity coupled with shock-induced  serotonin release [@marinesco2002a] produces long-lasting physiological changes, including enhanced excitability [@scholz1987c], spike narrowing [@antzoulatos2007], and facilitation of synaptic contacts with motor neurons [@frost1985].  With extensive training protocols, these physiological changes are accompanied by morphological changes, with the nociceptors sprouting new synapses and enlarging synaptic active zones [@bailey1983; @bailey1989; @wainwright2002].  The summative impact of these physiological and structural changes is the expression of long-term sensitization memory.  Consistent with this, blocking transcription during training also prevents long-term changes in synaptic strength [@castellucci1986] and synaptic outgrowth [@bailey1992].

## Analogs of sensitization memory can be observed in whole ganglia and in cell culture {#sec-analogs-of-sensitization-memory-can-be-observed-in-whole-ganglia-and-in-cell-culture}

The study of sensitization in *Aplysia* has been greatly facilitated by the development of analogs that can be studied in whole ganglia [e.g. @zhang1994] and cell culture [e.g. @montarolo1986], providing opportunities for both manipulation and measurement that would not be feasible when studying intact animals.  For cell culture, components of the defensive withdrawal circuits can be reconstituted by co-culturing sensory nociceptors with gill or siphon motor neurons, reproducing the direct glutamatergic pathway that strongly contributes to both normal withdrawal behavior and the encoding of sensitization memory.

In cellular studies, serotonin exposure is used to simulate sensitization training.  In both whole ganglia and in culture, serotonin produces the same distinctive patterns of plasticity in *Aplysia* nociceptors that help encode sensitization memory in intact animals, including enhanced excitability of the nociceptor sensory neuron and both short- and long-term synaptic facilitation of this sensory neuron-motor neuron synapse [@liu2011f; @montarolo1986].  Moreover, cellular models precisely recapitulate the phases of sensitization observed in intact animals: a single pulse of serotonin produces a rapid but transient increase in nociceptor excitability and synaptic strength that is unaffected by treatments that prevent transcription; 5 spaced pulses of serotonin produces a long-term facilitation of synaptic strength and the sprouting of new synapses, and these long-term effects depend on changes in neuronal transcription [@montarolo1986].  Even more striking, cellular models mirror the impact of pattern of training, with massed exposure of serotonin (a single prolonged exposure) ineffective at producing long-term changes [@mauelshagen1998], and some intermittently-spaced protocols producing especially strong changes [@Zhang2012Computational].
