# Encoding: What are the transcriptional changes induced by long-term sensitization training? {#sec-encoding-what-are-the-transcriptional-changes-induced-by-long-term-sensitization-training}

Successful long-term sensitization training protocols activate CREB1 and C/EBP while de-activating CREB2, triggering a transcriptional response that produces the cellular and synaptic changes required to encode a long-term sensitization memory.  What, exactly, is this transcriptional response and how is it organized?

A framework for answering this question was developed from tracking not transcription but translation.  Specifically, measurement of the rate of protein production in *Aplysia* nociceptors showed that serotonin produces two waves of increased translation: a small early wave evident within 1 hour that rapidly fades, and a larger late wave that arises more than 3 hours after the end of induction [@barzilai1989].  The early wave is part of the immediate-early response, as it persists through treatments that block transcription.   Subsequent studies have found that transcriptional changes are also organized into early and late waves, identifying transcripts that show rapid but transient changes in expression [@zwartjes1998], transcripts that show delayed changes in expression [@kuhl1992], and some that bridge these phases of regulation [@hart2011; @liu2011a]. 

The early and late waves have been further characterized via microarray studies conducted at different time points after long-term sensitization training (Figure 6).  These studies estimate that the early wave is focused, involving only about 50 transcripts [@Herdegen2014Characterization], that the late wave is complex, involving over 1,000 transcripts, and that very few (about 25) transcripts participate in both waves [@conte2017].  As sensitization memory is forgotten, the late wave also decays, but a handful of transcripts have been identified that remain regulated even beyond forgetting [@perez2018].

![**Time Course of Behavioral and Transcriptional Changes Following Long-Term Sensitization.** At top is the time-course of sensitization memory, showing both mean (solid lines) and individual (transparent lines) changes in defensive withdrawal durations on the trained (red) and untrained (sides) of Aplysia after long-term sensitization training (4 shocks). Sensitization memory is strongly expressed at 1 and 5 days after training, but fades back to baseline within 9 days. At bottom are log-fold changes in gene expression measured from microarray at 1 hour, 1 day, 5 days, and 7 days after the same long-term training protocol. Color-coding helps reveal the distinct patterns of regulation: There is an early-wave of transcripts up-regulated at 1 hour that then decays (blue), a large delayed wave of transcripts that show delayed up- or down-regulation at 1 day after training (purple with high transparency due to the large number of transcripts in this category), and a few transcripts that participate in both waves (green). Notably, most transcriptional changes resolve within 5 days of training, a time-point at which the expression of sensitization memory is still strong. A few transcripts, though, remain regulated even beyond forgetting (red). Behavioral data is replotted from Conte et al. (2017). Microarray data is synthesized from raw data posted from studies examining transcription 1 hour (Herdegen et al., 2014b), 1 day (Conte et al., 2017), and 7 days (Perez et al., 2018) after sensitization training.](Picture6.png){width="532"}

This section summarizes what is known about the transcriptional changes forming the early and late waves of regulation after the induction of long-term sensitization and its *in vitro* analogs.  Special focus is given to two interesting classes of transcriptional change: those that participate in both early and late waves of regulation, and those that persist even after sensitization is forgotten.

## The early wave of transcriptional change includes up-regulation of transcription factors, effector genes, and specific isoforms of CAM

Long-term sensitization training produces an immediate-early response that includes up-regulation of c/EBP.  Successful training stabilizes and extends this rapid phase of transcriptional change, but it remains transient, with c/EBP mRNA levels returning to baseline within 5 hours of induction. The early wave of transcription and translation detected after sensitization training consists of this immediate-early response and its subsequent stabilization and elaboration.

In addition to *c/EBP*, several specific transcripts in the early wave have been identified.  Some are transcription factors, with sensitization training producing rapid increases in the expression of transcripts that encode CREB1 [@bartsch1998] and a putative *Aplysia* homolog of C/EBPγ [aka Ig/EBP; @herdegen2014a].  In addition, several effector genes are regulated in the early wave of transcription.  This includes transcripts encoding *Aplysia* homologs of ubiquitin hydrolase [uch; @chain1999a; @hegde1997], calmodulin [@zwartjes1998], the peptide neurotransmitter sensorin [@sun2001], and an *Aplysia* Tolloid/BMP-1-like protein [@liu1997a].

There are probably additional transcriptional changes in the early wave, with a microarray analysis identifying over 50 additional transcripts showing rapid but transient regulation after sensitization training [@Herdegen2014Characterization].  Most of these additional transcripts have not yet been mapped to well-annotated gene models.  In addition, a microarray analysis conducted immediately after *in vivo* serotonin exposure in *Aplysia kurodai* identified regulation of 4 novel transcripts that were validated via qPCR: up-regulation of transcripts predicted to encode homologs of matrilin, antistasin, and eukaryotic translation initiation factor 3 (EIF3) and down-regulation of a BAT1 [@lee2008].  Time-courses were not evaluated, but EIF3 is likely one of the rare transcripts regulated both rapidly and persistently; it is discussed in [@encoding_both_waves].

One intriguing aspect of the early wave of transcription is that it can also produce changes in the expression of specific isoforms of the same gene.  Specifically, work in cell culture shows that serotonin treatment shifts the expression of different isoforms of mRNA for an *Aplysia* homolog of NCAM immunoglobulin-related cell adhesion molecule (ApCAM), changing the balance of isoform expression in *Aplysia* nociceptors and motor neurons without changing overall mRNA levels across all ApCAM isoforms [@schacher2000].  These changes in isoform expression require trans-synaptic interactions, as they only occur when sensory and motor neurons are co-cultured together.  Changes in both overall and synaptic ApCAM expression play critical roles in producing *in vitro* long-term sensitization, contributing to both transcription factor activation [@lee2007] and synapse formation [@zhu1995].  The changes in ApCAM isoform expression produced by serotonin suggests that the trans-isoform measurement of gene expression that has so far been common in *Aplysia* research may miss important forms of transcriptional regulation, pointing to an important priority for future research.

## The early wave of transcriptional response produces feedback loops that help stabilize and extend induction mechanisms

The immediate-early transcriptional response is initially fragile; it is extended and stabilized by complex interactions triggered by long-term training protocols.  This can be observed in the dynamics of the key immediate-early expression of c/EBP.  Even a short-term protocol (a single shock) is sufficient to produce a rapid increase in c/EBP transcription, but this fades in less than 1 hour, producing no lasting effects [@kopec2015a].  With repeated shock, c/EBP becomes upregulated for several hours [@yamamoto1999].  Treatments that prevent the stabilization of c/EBP expression impair the induction of long-term plasticity [@lee2012; @mirisis2021; @yim2006]; treatments that extend its activation enable short-term protocols to produce lasting effects [@kim2006a; @lee2001a]. 

Stabilization of the immediate-early response occurs, at least in part, through regulation of c/EBP activity and stability by MAPK isoforms.  First, c/EBP is phosphorylated by ERK, and this enables the binding of C/EBP to ERE motifs in its target genes [@yamamoto1999].  In addition, the p38 isoform of MAPK phosphorylates an *Aplysia* homolog of the RNA-binding protein embryonic lethal visual system (ELAV), protecting c/EBP mRNA from rapid degradation [@mirisis2021; @yim2006] that would otherwise occur from ARE/poly(U)-binding/degradation factor [AUF; @lee2012a].  These interactions integrate the extracellular signaling pathways contributing to ERK activation into the regulation of c/EBP: TrkB-receptor-activation is required for the initial increase in c/EBP transcription and NGF-B activation of P38 is required for the stabilization and extension of c/EBP transcription with long-term protocols [@kopec2015; @mirisis2021]. 

Stabilization of the early wave of transcription is also mediated by feedback between expressed genes and induction mechanisms.  For example, the rapid increase in the expression of uch degrades the regulatory subunit of PKA, extending the time during which the catalytic domain is active [@hegde1997a].  In addition, CREB1's promotion of its own expression extends CREB1 activity [@mohamed2005]; calmodulin mediates serotonergic activation of adenylyl cyclase [@lin2010]; sensorin secretion activates autoreceptors that help activate ERK [@hu2004a], and tolloid regulates TGF-β signaling that is also important for ERK activation [@chin1999].  Functional studies have confirmed that importance of these feedback loops, showing that the long-term persistence of serotonin-induced plasticity depends on upregulation of CREB1 [@liu2011c] and uch [@hegde1997] as well as signaling from TGF-β, which is activated by tolloid [@chin1999; @zhang1997].  For sensorin, serotonin produces not only a rapid but transient increase in its mRNA expression, but also export of sensorin mRNA to the neurites of nociceptors co-cultured with motor neurons, producing in increase in sensorin secretion that is essential for strengthening ERK activation and enabling serotonin to produce long-lasting plasticity [@hu2006]. Some negative-feedback may also possible, as C/EBPγ lacks a transcriptional activation domain and in other animals has been shown to act as a negative inhibitor C/EBP function [@cooper1995]; functional studies have not yet investigated this possibility. 

## The late wave is complex and involves changes potentially related to neural plasticity, protein production, mRNA transport, and meta-plasticity

Early proteomic screens showed that sensitization training and its *in vitro* analogs produce not only rapid changes in translation but also late-developing regulation, with several changes in expression becoming detectable only several hours after induction [@barzilai1989; @castellucci1988].  Intense work subsequently identified two of these late-regulated genes: *Aplysia* homologs of the calreticulin [@kennedy1992] and binding immunoglobin protein [BiP; @kuhl1992b], proteins involved in protein production and trafficking in the endoplasmic reticulum. 

The late phase of transcription may be surprisingly complex, with microarray identifying 1,172 transcripts that show clear regulation that does not develop until 1 day after long-term sensitization training [@conte2017a].  In contrast to the early wave consisting almost exclusively of up-regulation, late-regulated transcripts were both up-regulated (722, 62%) and down-regulated (450, 38%).  Given that the current draft of the *Aplysia* genome contains around 19,000 protein-coding gene models, the formation of a long-term sensitization memory is thus accompanied by regulation of an appreciable fraction of the genome.  One caution to this conclusion is that proteomic screens have not uncovered the same degree of complexity, identifying just over 30 proteins showing clear changes in expression 1 or 2 days after treatment with serotonin [@monje2012; @monje2013].  The reason for this discrepancy is not yet clear. It could be that not all transcriptional changes lead to translational changes, or it may be that changes in protein expression may be too subtle to easily detect, perhaps due to localization via transport and synapse-specific translation. 

Although the late wave of transcriptional change is complex, some overall regulatory themes seem apparent.  As might be expected, many late-regulated transcripts seem related to changes in neuronal signaling that could help express long-term sensitization memory.  For example, there is a sharp up-regulation in mRNA and protein levels of an *Aplysia* homolog of synaptotagmin [@conte2017a; @monje2012], a protein which plays a conserved role in regulating neurotransmitter release [@fernández-chacón2001].  There is also an increase in transcription of an putative glutamate receptor [@conte2017a].  It is feasible that these changes contribute to increases in synaptic connectivity that help express sensitization.  Indeed, two of the hallmarks of *in vitro* sensitization are long-term increases in nociceptor transmitter release and post-synaptic glutamate sensitivity [@trudeau1995; @zhu1997].  Other potential changes relevant to neural signaling include transcripts annotated to encode proteins involved in synaptic targeting (e.g. semaphorin), growth-factor signaling (e.g. TGF-β receptor-associated protein), ion channels (e.g. volage-gated potassium channel subunit), and synaptic plasticity (e.g. menin-like, insulin-like growth factor 2, and fibroblast growth factor receptor 4 like).  At the protein level, serotonin produces an increase in the expression of an *Aplysia* homolog of flotillin-1, which plays an important role in synapse formation and hippocampal-based memory formation in mammals [@monje2013a].

Beyond specific changes in neuronal signaling, many late transcriptional changes seem related to the infrastructure required to produce neuronal plasticity [@conte2017a].  That is, many of the transcriptional changes would be expected to foster the production, maturation, and trafficking of proteins, potentially providing the resources necessary to produce the signaling changes that encode sensitization.  This includes up-regulation of putative *Aplysia* homologs of proteins related to transcription (e.g. RNA polymerase II elongation factor ELL-like), RNA processing (e.g. CUGBP Elav-like family member 3-B), translation (e.g. Translational activator GCN1) and post-translational processing (e.g. BiP).   Especially notable is a widespread increase in the expression of translation initiation factors (eIF1, eIF2, eIF3, eIF4, and eIF5).  Consistent with a global increase in protein production, studies in culture show a late-developing down-regulation of CREB2 mRNA produced through serotonergic activation of small non-coding RNAs that interact with the protein Piwi to repress CREB2 transcription [@rajasethupathy2012].

Although there seems to be a global increase in the infrastructure for protein production, this does not rule out the possibility of synapse-specific changes should mRNAs be transported and targeted for local translation.  Consistent with this possibility, long-term sensitization also produces delayed up-regulation of several transcripts annotated to encode heterogeneous nuclear ribonucleoproteins and one annotated to encode a KIF protein (GenBank: EB225867.1); some of these changes are also detectable in proteomic screens [@monje2012].   As these proteins are all implicated in neuronal mRNA transport [@hirokawa2006], regulation of their expression could relate to targeting translational changes to specific synapses [@wang2010].

A fourth theme of the late phase of transcription is meta-plasticity: transcriptional changes that could feasibly be involved in resetting thresholds for additional learning and plasticity.  Specifically, microarray analysis indicates delayed down-regulation of several transcripts associated with the induction of long-term sensitization [@conte2017a].  This includes decreases in the expression of 3 of the 4 known *Aplysia* homologs of adenylate cyclase, a type-4 cAMP-specific phosphodiesterase (PDE4) critical to the activation of cAMP (Park, 2005), and a putative serotonin receptor transcript.  This set of transcriptional changes suggests the possibility that long-term sensitization makes it harder to induce additional sensitization.  If sensitization produces a new learning context, this could help explain reconsolidation effects that have been observed after training [@cai2012].

## A small and diverse set of transcripts participate in both the early and late waves of transcription {#encoding_both_waves}

Although long-term sensitization produces distinct early and late waves of transcription, some transcripts participate in both phases of regulation, showing changes in expression that begin rapidly but also persist for at least 1 day after training.  This is likely to be a rare form of regulation, with microarray analysis after sensitization training identifying only 25 potential "early-but-persistent" transcripts [@conte2017a].  Those that are well characterized are diverse, including transcription factors (CREB1 and Egr), synaptic proteins (synapsin), regulators of gene expression (eIF3 and TOB1), and modulatory peptide transmitters (FMRFa).   

The early-but-persistent transcripts are of special interest, as their continued regulation suggests they may play some essential role in long-term sensitization.  In particular, transcriptional changes involved in maintaining sensitization memory would be expected to show this type of stable regulation.   Functional analysis of several "early-but-persistent" bears out this interest, demonstrating essential roles in *in vitro* analogs of sensitization.

One of the first "early-but-persistent" transcripts to be identified was synapsin [@hart2011a], a protein that regulates synaptic vesicles.  In culture, repeated pulses of serotonin produce an immediate increase in synapsin mRNA that decays to a moderate down-regulation at 12 hours and then rises back to strong up-regulation within 1 day, indicating that synapsin is part of both the early and late waves of transcription.  These changes are likely mediated by activation of CREB1, as serotonin promotes binding of CREB1 to a CRE-like site in the *synapsin* promoter.  Transcriptional changes in synapsin are accompanied by a rapid rise in synapsin protein that within 24 hours is targeted specifically to synaptic varicosities in *Aplysia* nociceptors.  Synapsin likely plays a critical role in long-term sensitization, as RNA interference timed to prevent changes in synapsin expression prevent serotonin from producing lasting synaptic facilitation. 

eIF3 also shows early-but-persistent transcriptional activation.  It was initially identified for showing a rapid increase in expression following *in vivo* serotonin exposure in intact animals [@lee2008a], and subsequent study showed it is also persistently up-regulated after long-term sensitization training [@conte2017a].  Consistent with the importance of this class of transcripts, work in culture shows that knockdown of eIF3 expression via RNA interference prevents the long-term synaptic effects of serotonin, while over-expression enables short-term protocols to produce lasting effects [@lee2008a].

A third well-characterized early-but-persistent transcript is an *Aplysia* homolog of early-growth response protein [Egr; @cyriac2013], a transcription factor that plays a key in long-term plasticity and memory in mammals [@poirier2008].  Egr mRNA is constitutively expressed throughout the nervous system and is bi-directionally regulated by changes in neural activity.   Long-term sensitization produces a rapid and sustained increase in Egr mRNA in *Aplysia* nociceptors [@herdegen2014b].  Although the function of Egr regulation has not yet been explored, the degree of up-regulation 1 day after training is correlated with the strength of memory expression at that time point [@cyriac2013].

Although already discussed as an early-wave transcript, CREB1 may be another transcript that participates in both early and late waves.  CREB1 binds to its own promoter [@mohamed2005].  In cell culture, repeated pulses of serotonin produce both a rapid increase in CREB1 mRNA that decays quickly and a delayed increase that lasts at least 1 day [@liu2008].  This is accompanied by a long-lasting increase in the expression of CRE-containing promoters and is essential for serotonin to produce long-lasting increases in synaptic strength and excitability in *Aplysia* nociceptors [@liu2011d].  As discussed in the Maintenance section, the positive-feedback loop of CREB1 may serve not only to help stabilize the induction of long-term sensitization, but also to help maintain the persistence of sensitization memory.  One caveat to this conclusion, however, is that in intact animals, CREB1 seems participate only in the first wave, with multiple samples failing to observe persistent changes in CREB1 mRNA after long-term sensitization training [@bonnick2012; @conte2017a; @herdegen2014]. 

A surprising member of the early-but-persistent category is a transcript encoding the peptide neurotransmitter Phe-Met-Arg-Phe NH2 [FMRFa; @schaefer1985].  This transcript is strongly up-regulated 1 hour and 1 day after long-term sensitization training in the pleural ganglia, which contain FMRF-amidergic neurons that provide inhibitory neuromodulation to defensive withdrawal circuits.  This is accompanied by a late up-regulation of a FMRFa receptor in the pleural ganglia, suggesting an overall up-regulation of signaling from this transmitter system after sensitization.  These changes are surprising because FRMFa can suppress memory [@fioravante2006], producing antagonistic effects on the expression of long-terms sensitization memory [e.g. @abrams1984].  This suggests that in addition to activating transcriptional changes to encode sensitization memory, learning also activates signaling pathways that could eventually erode the expression of sensitization, a form of active forgetting [@berry2014]. 

Microarray analysis has identified 21 additional transcripts which show clear regulation at both 1 hour and 1 day after long-term sensitization [@conte2017a].  Some of these map to gene models that have not yet been well annotated.  Those with annotations include ApGlyT2 (sodium- and chloride-dependent glycine-dependent transport 2), ApVPS36 (Vacuolar protein-sorting-associated protein 36-like), and a putative *Aplysia* homolog of TOB1 (transducer of ErbB-2).   TOB1 is necessary for some forms of memory and is a key regulator of CPEB, a prion-like protein that plays a key role in the maintenance of the forms oflong-term plasticity that help encode sensitization memory (see @sec-maintenance). 

## The late wave of transcription fades before forgetting is complete, but some transcripts remain regulated long-after sensitization is forgotten

Unless training is extensive, long-term sensitization memory is forgotten, becoming progressively less likely to be recalled.  The late wave of transcription also fades, but seems to collapse before forgetting is completed.  Microarray analysis shows that less 1% of the transcripts identified in the late wave remain regulated just 5 days after training, a time point at which sensitization memory has partly decayed but remains quite strong [@rosiles2019].  This held true even in a subset of animals selected for especially strong maintenance of sensitization memory. 

Although the vast majority of transcriptional changes induced by sensitization training decay, a handful of transcripts show very persistent regulation that extends well beyond the behavioral expression of sensitization memory [@patel2018; @perez2018a].  While initially identified via exploratory microarray analysis, beyond-forgetting regulation has now been confirmed via qPCR in multiple independent samples.  This includes upregulation of FMRFa, BiP, and 3 un-annotated transcripts and down-regulation of a putative homolog of spectrin and an un-annotated transcript.  All of these are late-wave transcripts except FMRFa, which, as discussed above, is a an early-but-persistent transcript expected to work *against* the expression of sensitization memory. 

It is not yet clear why some transcriptional changes might persist after sensitization memory is forgotten.  They could be involved in producing forgetting, in maintaining a limited engram to enable rapid re-learning, or could even have no functional consequences at all. 
