# Abstract

The induction of a long-term memory requires both transcriptional change and neural plasticity.   Many of the links between transcription and memory have been revealed through the study of long-term sensitization in the *Aplysia* genus of marine mollusk*s*.  Sensitization is an evolutionarily conserved non-associative form of pain memory in which a painful stimulus (e.g. a strong electrical shock) produces an increase in arousal and defensive behavior.  *Aplysia* have proven useful for studying sensitization because it has been possible to trace the neural circuits that help encode sensitization memory and to simulate sensitization in neuronal cell cultures. 

One notable feature of sensitization in *Aplysia* is that only some training protocols initiate transcription and produce long-term memory; others fail to activate transcription and produce only short-term memories.   This occurs because the induction of long-term sensitization requires activation of two signal-transduction pathways that regulate transcription: 1) a fast but transient activation of the cAMP/PKA pathway that activates the transcription factor CREB1, and 2) delayed activation of the ERK isoform of MAPK that de-activates the transcriptional repressor CREB2.  The effectiveness of different training protocols is based on the degree to which activation of these pathways is synchronized.  The cAMP/PKA and MAPK pathways are complex, involving extracellular and trans-synaptic signaling, feedback loops, and cross-talk.  It has proven possible, though, to model transcriptional activation with enough fidelity to generate *in silico* predictions for optimized learning that have been validated in cell culture and intact animals.

Training protocols that successfully activate CREB1 while de-activating CREB2 produce a complex transcriptional cascade that helps encode long-term sensitization memory.  The transcriptional cascade involves a focused wave of immediate-early transcriptional activations.  This includes activation of additional transcription factors, such as C/EBP, as well as effectors such as uch, sensorin, and tolloid/BMP-1.  These early transcriptional changes close feedback loops that help extend and stabilize the early wave of transcriptional changes, triggering a much broader late wave of transcriptional changes that develops within 1 day of training.  The late wave involves transcripts likely to alter neural signaling, increase protein production, transport mRNAs, and induce meta-plasticity.  A small set of transcripts participate in both the early and late waves of transcriptional change, and several of these (CREB1, synataxin, eIF4) have been shown to play essential roles in completing the induction of long-term sensitization.  Most transcriptional changes fade as sensitization memory is forgotten, but some changes persist beyond forgetting, including a long-lasting up-regulation of an inhibitory peptide transmitter that could foster forgetting.

The maintenance of long-term sensitization may involve self-sustaining transcriptional feedback loops.  In particular, CREB1 binds to its own promoter, producing a long-lasting increase in CREB1 mRNA, protein, and gene activation that is essential for sustaining cellular correlates of sensitization for at least 1 day after induction.  Multiple puzzles about maintenance remain to be solved though, including how long transcriptional loops might play a role in maintenance, how they might interact with other maintenance mechanisms, and how transcriptional states relate to long-term sensitization memory during forgetting. 

Many aspects of the induction, stabilization, and maintenance of sensitization memory in *Aplysia* are conserved, suggesting it will continue to be a fruitful simpler system for understanding the physical basis of lasting memory.

# Preprint {.unnumbered}

This is a preprint posted to [PsyArxiv](https://osf.io/preprints/psyarxiv/), available for download at: <https://osf.io/urxk2/>. Please cite as:

Wilsterman, T., Calin-Jageman, R., & Calin-Jageman, I. E. (2023, October 3). Transcriptional Regulation Underlying Long-term Sensitization in Aplysia. https://doi.org/10.31219/osf.io/urxk2

This preprint was created using Quarto and RStudio. The underlying markdown documents are posted to [GitHub](https://github.com/rcalinjageman/LTS_and_Transcription_Review/tree/main), and an html version is available here: <https://rcalinjageman.github.io/LTS_and_Transcription_Review/>

The final published article is available in the *Oxford Research Encyclopedia of Neuroscience:* <https://oxfordre.com/neuroscience> 

# Version History {.unnumbered}

-   Version 1.1 - Posted October 3 - Word version

-   Version 1.2 - Posted November 18 - Pdf version after conversion to Quarto format. Still need to review for typos and check references. For pdf version, some

-   Version 1.3 - Posted on November 19 - Fixed duplicated references and switched to APA7 citations
