---
bibliography: references.bib
csl: apa-7th-edition.csl
---

# Introduction

Long-term memory---the long-lasting modification of behavior based on prior experience---is a core feature of animal life [@abramson1994].  The persistence that characterizes long-term memory can be remarkable: despite constant molecular turnover in the nervous system, long-term memories can last decades [@bahrick1984].  Most long-term memories, however, are not so stable: the majority are forgotten, becoming progressively less likely to be recalled [@squire1989].  Surprisingly, forgotten does not mean deleted: the right cue or a brief re-exposure to learning material can often re-activate the expression of a long-term memory [@ebbinghaus1885], suggesting that at least some aspect of the memory persists even when recall is no longer possible.  Long-term memory thus presents an intriguing set of mysteries for neuroscience: it is a form of storage in the nervous system which can be remarkably durable, yet which is most often disrupted in some profound but not complete way.

Intensive study of long-term memory has begun to shed light on these mysteries.  One area of consensus is that the induction of a long-term memory requires both transcriptional change and neural plasticity [@goelet1986].  That is, experiences sufficient to induce long-term memory also alter neuronal gene expression, activating transcription factors and other gene regulatory mechanisms to change the steady-state mRNA levels of specific transcripts in the nervous system and thus the cellular context for neuronal protein expression.  These transcriptional changes are essential for the development of long-lasting forms of neuronal plasticity that encode long-term memories, producing changes in excitability, synaptic strength, connectivity, and other aspects of neuronal signaling.  The linkage between long-term memory and transcriptional change is now so well-established that it has become part of the taxonomy of learning: a memory is considered long-term if it requires changes in neural transcription.

This general idea of long-term memory depending on altered gene expression raises important questions.  One outstanding issue is selective encoding: why do only some experiences activate transcription to create enduring memories?  A second issue to resolve is the nature of the transcriptional response: what, exactly, are the transcriptional changes that occur and how are they organized?  This has proven difficult to address in part because neural representations of long-term memory are sparse, so the transcriptional signal can be noisy.  A third, and contentious, issue is the role transcription plays in the expression of long-term memory: beyond triggering encoding, how do transcriptional states relate to maintenance, forgetting, and re-acquisition of long-term memory?  This article summarizes the developing answers to these questions that have been gleaned from the study of long-term sensitization in *Aplysia californica*, a research paradigm that has been instrumental in shedding light on the neural mechanisms of memory. 
