# Maintenance: Does transcription contribute to the long-term maintenance of sensitization memory?  {#sec-maintenance}

Long-term sensitization training produces a robust transcriptional response, and these transcriptional changes are essential to the long-term neuronal changes that encode a sensitization memory.  From that point, the sensitization memory can persist for days to weeks, though even when sensitization memory seems to have fully faded it can be rapidly re-learned [@menges2015; @philips2006].  How is the sensitization memory maintained and what happens to maintenance memory during forgetting and re-learning? 

Given the constant molecular flux that characterizes life, researchers have presumed that the long-lasting expression of memory must involve one or more maintenance mechanisms: molecular interactions that are a) inducible by learning, b) self-sustaining throughout the life of the memory, and c) responsible for the continued expression of a sensitization memory.   According to this conceptualization, disrupting a maintenance mechanism would halt the expression of a long-term memory, even long after initial training.   There are not clear predictions of how maintenance mechanisms would relate to forgetting: it could be that forgetting represents a disruption of maintenance, or it could be that maintenance mechanisms persist but that additional processes develop that inhibit the continued expression of the memory.   Although the notion of a maintenance mechanism makes sense, it has proven difficult to develop definitive accounts of memory maintenance for long-term sensitization in *Aplysia*.  In this section, potential maintenance mechanisms are reviewed, touching briefly on some non-transcriptional mechanisms and then considering in more depth the possibility of transcriptional loops that help sustain long-term memory [For an in-depth review, see @smolen2019].

## Self-sustaining protein interactions could serve as maintenance mechanisms for long-term sensitization memory

At least some aspects of sensitization maintenance occur through self-sustaining protein interactions.  For example, PKC, which helps mediate short-term sensitization, can become cleaved by calpain into a truncated, constitutively active form, termed PKM, which can then persistently regulate synaptic strength.  PKMs play a role in memory maintenance, as treatments that disrupt PKMs stop the maintenance of long-term sensitization in intact animals [@cai2011] and of its cellular analogs in cell culture [@farah2019; @hu2017].

In addition, serotonin produces a self-perpetuating conformational change in synaptically-expressed CPEB, a prion-like protein that regulates local translation [@miniaci2008; @si2003; @si2010].  This enables activated synapses to up-regulate local translation.  Synapse-specific depletion of CPEB shows that it is essential to initial maintenance (1 to 2 days after induction) of both synaptic facilitation and synaptic outgrowth, but that maintenance eventually becomes independent of CPEB function (3 days post induction).

## Transcriptional loops could also support memory maintenance, including the inducible auto-activation of CREB1

Self-sustaining protein interactions may be especially important for maintaining synapse-specific encoding of sensitization.  Sensitization is also encoded by global changes in neuronal function, including a long-term enhancement of excitability in *Aplysia* nociceptors [@scholz1987c].  This suggests the possible operation of neuron-wide maintenance mechanisms.   Given that the induction of sensitization is stabilized and extended by transcriptional feedback loops, this raises the possibility that these loops continue to operate after induction to produce sustained neuron-wide changes in function.

The most well-explored possibility relates to the inducible auto-activation of CREB1.  As described above, studies in culture show that CREB1 produces a self-sustaining transcriptional loop: induction produces CREB1 phosphorylation and increases binding of CREB1 to its own promoter, producing a long-term increase in CREB1 mRNA, CREB1 protein, and the transcription of CREB1 [@liu2008b; @liu2011f; @mohamed2005]. Moreover, RNA interference designed to block the late up-regulation of CREB1 mRNA stops the maintenance of increased synaptic strength and excitability.  Thus, there is strong evidence that CREB1-self-promotion plays an essential role in at least the early phases of sensitization maintenance.  There may be additional transcriptional feed-back loops that contribute to sensitization maintenance (e.g. PKA induction of uch transcription, which extends the activity of PKA). 

There are several challenges to the notion of transcriptional feedback loops for sensitization maintenance.  First, while CREB1 mRNA is persistently up-regulated by serotonin treatment in culture, multiple attempts have failed to detect persistent up-regulation in intact animals following long-term sensitization training [@bonnick2012; @conte2017a; @herdegen2014d].  A more significant challenge is that it is not yet clear if persistent transcription is always required for the expression of long-term sensitization memory.  To date, few analyses have extended more than 1 day after induction, a timepoint that may be more associated with memory stabilization than memory maintenance [@miniaci2008].  Moreover, microarray analysis suggests that the late wave of transcription almost fully collapses before forgetting [@Rosiles2019Transcriptional], and that reminders can produce a long-term reinstatement of sensitization without re-activating the late wave of transcription [@rosiles2020].  These analyses might lack sensitivity, but they raise the intriguing possibility that sensitization memory can be expressed in the absence of ongoing transcriptional changes.

These challenges are not definitive.  One possibility is that persistent transcriptional changes become refined as sensitization memory matures, and can no longer be detected in whole ganglia via low-sensitivity screening techniques.  This could be especially true if persistent transcriptional states develop only in sparse sets of memory-encoding neurons, and could even be obscured if non-encoding neurons undergo offsetting homeostatic changes.  If this is correct, persistent transcriptional regulation of CREB1 or other feedback-loop transcripts should be detectable via single-cell transcriptional analysis. 

Another possible explanation is that long-term sensitization has multiple forms that differentially depend on transcriptional maintenance mechanism.  At the behavioral level, very intense training (4 spaced shocks each day for 4 days) produces sensitization memory that lasts for weeks and that is always accompanied by synaptic outgrowth [@bailey1989].  Less intense training (4 spaced shocks on 1 day only) produce sensitization that decays within a week and does not produce detectable levels of synaptic outgrowth [@wainwright2002]. This suggests the possibility of a very-long-lasting phase of sensitization memory produced only with extended training.  It may be that only this very long-lasting phase requires persistent transcriptional changes, as only this phase involves maintained growth.   The discrepancy in CREB1 dynamics between culture and intact animals could reflect differential recruitment of these phases on long-term sensitization: *in vitro* models always produce synaptic growth and therefore may reflect primarily a very-long-lasting form of sensitization, whereas transcriptional analyses from intact animals have so far utilized only a 1-day training protocol, and may therefore have missed persistent up-regulation of transcription in general and CREB1 specifically.  If so, transcriptional analysis following more intense training should support the transcriptional-loop model.

## Sensitization memory may be maintained via multiple interacting maintenance mechanisms involving changes in protein function, transcription, and epigenetic regulation

In addition to feedback loops, persistent changes in transcription could be maintained by epigenetic modifications.  Indeed, *in vitro* sensitization produces an increase in methylation of a region of the CREB2 promoter, leading to a persistent decrease in CREB2 expression [@rajasethupathy2012].  In addition, pharmacological inhibition of DNA methylation stops maintenance of *in vitro* sensitization, though what transcriptional changes this treatment targets have not been identified.

At this time, there is evidence for self-sustaining maintenance mechanisms operating at the protein level (PKMs and possibly also CPEB), via transcriptional loops (CREB1), and through epigenetic regulation.  Rather than considering these mutually exclusive possibilities, it has been proposed that the sustained expression of sensitization memory reflects multiple, interlinked maintenance mechanisms, and that it is their interoperation that sustains the complex patterns of plasticity that express long-term memory [@smolen2019].  In grappling with this complexity, it remains unclear how maintenance mechanisms might change (if at all) during forgetting, and/or how rapid re-learning after forgetting is possible. 
